### ISSUE TITLE
Implement "delete_file"

### ISSUE THREAD

**Issue by FelipeFranke5** [parneetsingh022/fileosninja#11]
I search through the docs to check if is there a function to delete an existing file using the fileosninja module, but I couldn't find it. Is there any specific reason for not including it? If not, would be an interesting feature.

**Comment by FelipeFranke5** [comment]
Oh, I just read through the issues, apparently you already have this in mind. Let me know If you'd like any help implementing it.

**Comment by parneetsingh022** [comment]
@FelipeFranke5 Hi, You can work on it if you want.
