### ISSUE TITLE
Create few python functions in `file_manager.py`

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/fileosninja#2]
Write following functions in file_manager.py

**Note** : Make sure not to push these to `main` branch, create a new branch.

All of these functions must have proper docstrings (refer to the docstrings of already existing functions).
- is_file(file_name) - checks whether the file exists or not.
- is_folder(folder_name) - checks whether the folder exists.
- list_files(address) - lists all the file in the given address (not folders)
- list_folders(address) - list all the folders at given address (not files)
- list_all(address) - list both files and folders at given address
- delete_file(file_name) - This function deletes the file.
- copy_to(file_name, destination_folder) - Copies the file to the destination folder.
- copy_file(file_name, new_file_name) - Copies the file to a new file at given location.

**How to test the module?**
The testing procedure involves using a file named test.py, which is explicitly excluded from version control via the .gitignore configuration. Consequently, any files generated within the test folder will also be excluded from version control and, thus, will not be pushed to the repository. (**Note**: The folder specified is test folder not tests folder. `tests` folder has unit tests)

**Comment by Sherwin-14** [comment]
Can you assign this to me ?

**Comment by parneetsingh022** [comment]
Sure
