### ISSUE TITLE
Function to display folder structure.

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/fileosninja#3]
Create a file `utils.py` in fileosninja module. Make a method (be creative with the name) that will display the folder structure of a given folder. 

**Note** : Make sure not to push these to `main` branch, create a new branch.

Function must have proper docstrings (refer to the docstrings of already existing functions inf `file_manager.py`).

eg. func_name(folder_address, depth=3)
The depth keyword refers to the level of depth or hierarchy to which the folder structure should be displayed, default value should be 3.

output:
<img width="124" alt="Screenshot 2024-01-02 212755" src="https://github.com/parneetsingh022/fileosninja/assets/99793808/14fad8b7-cd42-4756-9c8a-6527bdb0ef97">

**How to test the module?**
The testing procedure involves using a file named test.py, which is explicitly excluded from version control via the .gitignore configuration. Consequently, any files generated within the test folder will also be excluded from version control and, thus, will not be pushed to the repository.  (**Note**: The folder specified is test folder not tests folder. `tests` folder has unit tests)

**Comment by alenachao** [comment]
hi! i'd like to work on this, can you assign it to me?

**Comment by parneetsingh022** [comment]
@alenachao Yeah sure

**Comment by parneetsingh022** [comment]
@alenachao Great it works. Thanks for working on it.
